"""
Tests using fixtures generated from real OpenAI ingestion.
These tests demonstrate the timezone correction scenario using actual OpenAI-generated knowledge base articles.
"""
from django.test import TestCase
from django.contrib.auth.models import User
from django_ergo.models import Knowledgebase, Article, UserChat, ChatMessage, Workflow
from shop.ingestion import format_chat_history, run_chat_history_ingestion


class OpenAIGeneratedFixtureTests(TestCase):
    """Tests using fixtures created from real OpenAI ingestion."""
    
    fixtures = ['openai_generated_scenario.json']
    
    def setUp(self):
        """Set up test data from OpenAI-generated fixtures."""
        self.user = User.objects.get(username='shop_owner')
        self.kb = Knowledgebase.objects.get(name='Shop Wiki')
        self.workflow = Workflow.objects.get(name='DB Admin Assistant')
        
    def test_openai_generated_fixture_data_loaded(self):
        """Test that OpenAI-generated fixture data loads correctly."""
        # Verify user exists
        self.assertEqual(self.user.username, 'shop_owner')
        self.assertEqual(self.user.email, 'owner@example.com')
        
        # Verify knowledge base exists  
        self.assertEqual(self.kb.name, 'Shop Wiki')
        self.assertEqual(self.kb.owner_id, str(self.user.id))
        
        # Verify workflow exists
        self.assertEqual(self.workflow.name, 'DB Admin Assistant')
        self.assertIn(self.kb, self.workflow.knowledgebases.all())
        
        # Verify chat conversations exist
        chats = UserChat.objects.filter(user=self.user)
        self.assertGreaterEqual(chats.count(), 2)  # At least the timezone correction chat
        
        # Verify OpenAI-generated articles exist
        articles = Article.objects.filter(knowledgebase=self.kb)
        self.assertGreater(articles.count(), 0)
        
        print("✅ All OpenAI-generated fixture data loaded correctly")
    
    def test_openai_timezone_article_content(self):
        """Test that OpenAI generated realistic timezone configuration content."""
        # Find the timezone article generated by OpenAI
        timezone_article = Article.objects.filter(
            knowledgebase=self.kb,
            title__icontains='timezone'
        ).first()
        
        self.assertIsNotNone(timezone_article, "OpenAI should have generated a timezone article")
        
        # Verify it contains the key information from the correction scenario
        content = timezone_article.content.lower()
        self.assertIn('est', content, "Article should mention EST timezone")
        self.assertIn('timezone', content, "Article should discuss timezone")
        self.assertIn('sales', content, "Article should relate to sales queries")
        
        # Verify it references the original correction
        self.assertIn('correction', content, "Article should mention the correction")
        self.assertIn('utc', content, "Article should reference the original UTC assumption")
        
        print(f"✅ OpenAI generated realistic content: {timezone_article.title}")
        print(f"   Content preview: {timezone_article.content[:100]}...")
    
    def test_timezone_correction_chat_sequence(self):
        """Test the timezone correction chat sequence from fixtures."""
        # Get the timezone correction chat
        correction_chat = UserChat.objects.filter(
            user=self.user,
            title__icontains='timezone correction'
        ).first()
        
        self.assertIsNotNone(correction_chat, "Should have timezone correction chat")
        
        # Verify the message sequence
        messages = list(correction_chat.messages.order_by('created_at'))
        self.assertGreaterEqual(len(messages), 4, "Should have at least 4 messages in correction sequence")
        
        # Check the correction pattern
        user_messages = [msg for msg in messages if msg.role == 'user']
        assistant_messages = [msg for msg in messages if msg.role == 'assistant']
        
        # Should have user asking for sales
        sales_request = any('sales' in msg.content.lower() for msg in user_messages)
        self.assertTrue(sales_request, "User should ask for sales data")
        
        # Should have user correcting timezone
        timezone_correction = any('est' in msg.content.lower() for msg in user_messages)
        self.assertTrue(timezone_correction, "User should correct to EST timezone")
        
        # Should have assistant acknowledging UTC initially
        utc_response = any('utc' in msg.content.lower() for msg in assistant_messages)
        self.assertTrue(utc_response, "Assistant should initially use UTC")
        
        print("✅ Timezone correction chat sequence verified")
    
    def test_learning_demonstrated_in_followup(self):
        """Test that learning is demonstrated in follow-up conversations."""
        # Find follow-up chats that show the learning worked
        followup_chats = UserChat.objects.filter(
            user=self.user,
            title__icontains='follow'
        )
        
        if followup_chats.exists():
            followup_chat = followup_chats.first()
            messages = list(followup_chat.messages.order_by('created_at'))
            
            # Look for EST usage in assistant responses
            assistant_messages = [msg for msg in messages if msg.role == 'assistant']
            est_usage = any('est' in msg.content.lower() for msg in assistant_messages)
            
            if est_usage:
                print("✅ Follow-up chat shows EST timezone learning")
            else:
                print("📝 Follow-up chat exists but may not show EST learning yet")
    
    def test_openai_ingestion_system_integration(self):
        """Test that the ingestion system integrates properly with OpenAI-generated data."""
        # Verify we can query the knowledge base for timezone information
        timezone_articles = Article.objects.filter(
            knowledgebase=self.kb,
            content__icontains='EST'
        )
        
        self.assertTrue(timezone_articles.exists(), "Should find EST-related articles")
        
        # Verify the articles are searchable and useful
        for article in timezone_articles:
            self.assertIn('EST', article.content)
            self.assertTrue(len(article.content) > 50, "Articles should have substantial content")
            self.assertTrue(article.hierarchy_code, "Articles should have hierarchy codes")
            
        print(f"✅ Found {timezone_articles.count()} timezone-related articles from OpenAI")
    
    def test_complete_ingestion_workflow_with_openai_data(self):
        """Test the complete workflow using OpenAI-generated fixtures."""
        print("\n" + "="*60)
        print("🧪 TESTING COMPLETE WORKFLOW WITH OPENAI DATA")
        print("="*60)
        
        # 1. Verify initial data exists
        chats = UserChat.objects.filter(user=self.user)
        print(f"\n📊 Initial state:")
        print(f"   User: {self.user.username}")
        print(f"   Chats: {chats.count()}")
        print(f"   KB: {self.kb.name}")
        
        # 2. Show the correction scenario
        correction_chat = UserChat.objects.filter(
            user=self.user,
            title__icontains='correction'
        ).first()
        
        if correction_chat:
            print(f"\n💬 Correction scenario:")
            for msg in correction_chat.messages.order_by('created_at'):
                print(f"   {msg.role.upper()}: {msg.content[:80]}...")
        
        # 3. Show OpenAI-generated knowledge
        articles = Article.objects.filter(knowledgebase=self.kb)
        print(f"\n📚 OpenAI generated knowledge:")
        for article in articles:
            print(f"   📄 {article.title} ({article.hierarchy_code})")
            print(f"      {article.content[:100]}...")
        
        # 4. Test that future queries would find this information
        timezone_info = Article.objects.filter(
            knowledgebase=self.kb,
            content__icontains='today\'s sales'
        )
        
        if timezone_info.exists():
            print(f"\n✅ Future sales queries will find timezone guidance!")
        else:
            print(f"\n📝 Articles exist but may not specifically mention 'today's sales'")
        
        # 5. Verify the learning loop is complete
        self.assertTrue(articles.exists(), "OpenAI should have created knowledge base articles")
        self.assertTrue(chats.exists(), "Should have chat history showing corrections")
        
        print(f"\n✅ COMPLETE INGESTION WORKFLOW VERIFIED!")
        print("="*60)


class OpenAIIngestionQualityTests(TestCase):
    """Tests that verify the quality of OpenAI ingestion results."""
    
    fixtures = ['openai_generated_scenario.json']
    
    def test_openai_article_quality(self):
        """Test that OpenAI-generated articles are high quality."""
        articles = Article.objects.all()
        
        for article in articles:
            # Test article structure
            self.assertTrue(article.title, "Articles should have titles")
            self.assertTrue(article.content, "Articles should have content")
            self.assertTrue(article.hierarchy_code, "Articles should have hierarchy codes")
            
            # Test content quality
            self.assertGreater(len(article.content), 50, "Articles should have substantial content")
            self.assertNotIn('lorem ipsum', article.content.lower(), "Should not contain placeholder text")
            
            # Test relevance to timezone scenario
            content_lower = article.content.lower()
            if 'timezone' in article.title.lower():
                self.assertIn('est', content_lower, "Timezone articles should mention EST")
                self.assertIn('sales', content_lower, "Should relate to sales queries")
                
        print(f"✅ Verified quality of {articles.count()} OpenAI-generated articles")
    
    def test_openai_learned_business_context(self):
        """Test that OpenAI learned the business context correctly."""
        # Find articles that show business understanding
        kb = Knowledgebase.objects.get(name='Shop Wiki')
        articles = Article.objects.filter(knowledgebase=kb)
        
        # Look for business-specific knowledge
        business_knowledge = []
        for article in articles:
            content = article.content.lower()
            if any(term in content for term in ['shop', 'business', 'sales', 'timezone', 'est']):
                business_knowledge.append(article)
        
        self.assertTrue(business_knowledge, "OpenAI should have learned business context")
        
        print(f"✅ OpenAI learned business context in {len(business_knowledge)} articles")
        for article in business_knowledge:
            print(f"   - {article.title}: Business context captured")
    
    def test_fixture_represents_realistic_scenario(self):
        """Test that the fixture represents a realistic business scenario."""
        # Verify we have a realistic e-commerce setup
        user = User.objects.get(username='shop_owner')
        self.assertEqual(user.first_name, 'Shop')
        self.assertEqual(user.last_name, 'Owner')
        
        # Verify realistic chat conversation
        chats = UserChat.objects.filter(user=user)
        self.assertTrue(chats.exists(), "Should have realistic chat conversations")
        
        # Verify realistic knowledge base
        kb = Knowledgebase.objects.get(name='Shop Wiki')
        self.assertIn('store', kb.description.lower())
        
        # Verify the scenario is coherent
        messages = ChatMessage.objects.filter(chat__user=user)
        self.assertTrue(messages.exists(), "Should have realistic message exchanges")
        
        print("✅ Fixture represents realistic e-commerce timezone correction scenario")