# Generated by Django 5.2.17 on 2026-10-05 01:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import ergonaut.utils.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_timezone_telegram"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiKey",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=ergonaut.utils.models._generate_medium_id,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("name", models.CharField(max_length=100)),
                ("hint", models.CharField(max_length=16)),
                ("key_hash", models.CharField(max_length=64, unique=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
