# Generated by Django 4.2.18 on 2025-07-18 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ergo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Workflow",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name for the workflow", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Description of what this workflow does"
                    ),
                ),
                (
                    "instructions",
                    models.TextField(help_text="System instructions for the AI agent"),
                ),
                (
                    "tools_config",
                    models.JSONField(
                        default=dict,
                        help_text="Configuration for tools available to this workflow",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this workflow is available for use",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "knowledgebases",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Knowledgebases this workflow can access",
                        related_name="workflows",
                        to="ergo.knowledgebase",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="UserChat",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="New Chat",
                        help_text="Title of the chat conversation",
                        max_length=255,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this chat is currently active"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        default=dict,
                        help_text="Additional metadata for the chat (user preferences, context, etc.)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who owns this chat",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        help_text="The workflow that processes messages in this chat",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chats",
                        to="ergo.workflow",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("user_input", "User Input"),
                            ("assistant_message", "Assistant Message"),
                            ("tool_request", "Tool Request"),
                            ("tool_response", "Tool Response"),
                            ("system_message", "System Message"),
                            ("error", "Error"),
                        ],
                        help_text="Type of message (user input, assistant response, tool call, etc.)",
                        max_length=20,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("assistant", "Assistant"),
                            ("system", "System"),
                            ("tool", "Tool"),
                        ],
                        help_text="Role of the message sender",
                        max_length=20,
                    ),
                ),
                ("content", models.TextField(help_text="The message content")),
                (
                    "metadata",
                    models.JSONField(
                        default=dict,
                        help_text="Additional metadata (tool calls, responses, error details, etc.)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chat",
                    models.ForeignKey(
                        help_text="The chat this message belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="ergo.userchat",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
