# Generated by Django 4.2.23 on 2025-07-24 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Human-readable name for the workflow', max_length=255)),
                ('description', models.TextField(help_text='Description of what this workflow does')),
                ('instructions', models.TextField(help_text='System instructions for the AI agent')),
                ('tools_config', models.JSONField(default=dict, help_text='Configuration for tools available to this workflow')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this workflow is available for use')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserChat',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='New Chat', help_text='Title of the chat conversation', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this chat is currently active')),
                ('metadata', models.JSONField(default=dict, help_text='Additional metadata for the chat (user preferences, context, etc.)')),
                ('workflow_state', models.JSONField(default=dict, help_text='Serialized workflow state for pause/resume functionality')),
                ('user', models.ForeignKey(help_text='The user who owns this chat', on_delete=django.db.models.deletion.CASCADE, related_name='chats', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(help_text='The workflow that processes messages in this chat', on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='django_ergo.workflow')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Knowledgebase',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('owner_id', models.CharField(blank=True, db_index=True, help_text='Owner identifier for multi-tenant support', max_length=255, null=True)),
                ('workflows', models.ManyToManyField(blank=True, help_text='Workflows that can access this knowledgebase', related_name='knowledgebases', to='django_ergo.workflow')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_type', models.CharField(choices=[('user_input', 'User Input'), ('assistant_message', 'Assistant Message'), ('tool_request', 'Tool Request'), ('tool_response', 'Tool Response'), ('system_message', 'System Message'), ('error', 'Error')], help_text='Type of message (user input, assistant response, tool call, etc.)', max_length=20)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System'), ('tool', 'Tool')], help_text='Role of the message sender', max_length=20)),
                ('content', models.TextField(help_text='The message content')),
                ('metadata', models.JSONField(default=dict, help_text='Additional metadata (tool calls, responses, error details, etc.)')),
                ('agent_context', models.JSONField(default=dict, help_text='Serialized OpenAI agent context for workflow continuity')),
                ('chat', models.ForeignKey(help_text='The chat this message belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='django_ergo.userchat')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hierarchy_code', models.CharField(db_index=True, default='0', help_text="The hierarchy code of the article, e.g. '012' (0th chapter, 1st section, 2nd sub-section) or 'C3' (12th chapter, 3rd sub-section)", max_length=16)),
                ('title', models.CharField(max_length=512)),
                ('content', models.TextField()),
                ('summary', models.TextField(blank=True, null=True)),
                ('knowledgebase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='django_ergo.knowledgebase')),
            ],
            options={
                'ordering': ['hierarchy_code'],
            },
        ),
        migrations.AddIndex(
            model_name='userchat',
            index=models.Index(fields=['user', '-updated_at'], name='django_ergo_user_id_77eca3_idx'),
        ),
        migrations.AddIndex(
            model_name='userchat',
            index=models.Index(fields=['workflow'], name='django_ergo_workflo_993f36_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgebase',
            index=models.Index(fields=['owner_id'], name='django_ergo_owner_i_4c4699_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgebase',
            index=models.Index(fields=['name'], name='django_ergo_name_f61f42_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['chat', 'created_at'], name='django_ergo_chat_id_10489c_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['message_type'], name='django_ergo_message_f10d88_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['knowledgebase', 'hierarchy_code'], name='django_ergo_knowled_094e64_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['hierarchy_code'], name='django_ergo_hierarc_b752b8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='article',
            unique_together={('knowledgebase', 'hierarchy_code')},
        ),
    ]
