# Generated by Django 4.2.23 on 2025-07-26 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ergo', '0002_add_vector_indexes'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='article',
            table_comment='Articles with semantic embeddings and pgvector indexes for fast similarity search',
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(choices=[('user_input', 'User Input'), ('assistant_message', 'Assistant Message'), ('tool_request', 'Tool Request'), ('tool_response', 'Tool Response'), ('tool_approval_request', 'Tool Approval Request'), ('tool_approval_response', 'Tool Approval Response'), ('workflow_paused', 'Workflow Paused'), ('workflow_resumed', 'Workflow Resumed'), ('system_message', 'System Message'), ('error', 'Error')], help_text='Type of message (user input, assistant response, tool call, etc.)', max_length=30),
        ),
    ]
