# Generated by Django 5.2.6 on 2026-03-30 21:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ergo', '0003_add_approval_message_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('engine_type', models.CharField(choices=[('claude', 'Claude'), ('openai', 'OpenAI')], max_length=20)),
                ('transport_type', models.CharField(choices=[('cli', 'CLI'), ('api', 'API')], max_length=20)),
                ('session_id', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_sessions', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversation_sessions', to='django_ergo.workflow')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClaudeMessage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=20)),
                ('stop_reason', models.CharField(blank=True, max_length=30, null=True)),
                ('input_tokens', models.IntegerField(blank=True, null=True)),
                ('output_tokens', models.IntegerField(blank=True, null=True)),
                ('sequence', models.IntegerField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claude_messages', to='django_ergo.conversationsession')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='OpenAIMessage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System'), ('tool', 'Tool')], max_length=20)),
                ('content', models.TextField(blank=True, null=True)),
                ('tool_calls', models.JSONField(blank=True, null=True)),
                ('tool_call_id', models.CharField(blank=True, max_length=255, null=True)),
                ('function_name', models.CharField(blank=True, max_length=255, null=True)),
                ('input_tokens', models.IntegerField(blank=True, null=True)),
                ('output_tokens', models.IntegerField(blank=True, null=True)),
                ('sequence', models.IntegerField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='openai_messages', to='django_ergo.conversationsession')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='ClaudeContentBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block_type', models.CharField(choices=[('text', 'Text'), ('tool_use', 'Tool Use'), ('tool_result', 'Tool Result'), ('thinking', 'Thinking')], max_length=20)),
                ('sequence', models.IntegerField()),
                ('text', models.TextField(blank=True, null=True)),
                ('thinking', models.TextField(blank=True, null=True)),
                ('tool_use_id', models.CharField(blank=True, max_length=255, null=True)),
                ('tool_name', models.CharField(blank=True, max_length=255, null=True)),
                ('tool_input', models.JSONField(blank=True, null=True)),
                ('tool_result_for', models.CharField(blank=True, max_length=255, null=True)),
                ('tool_result_content', models.JSONField(blank=True, null=True)),
                ('is_error', models.BooleanField(default=False)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='django_ergo.claudemessage')),
            ],
            options={
                'ordering': ['sequence'],
                'indexes': [models.Index(fields=['message', 'sequence'], name='django_ergo_message_c1c8c1_idx'), models.Index(fields=['block_type'], name='django_ergo_block_t_307e92_idx'), models.Index(fields=['tool_name'], name='django_ergo_tool_na_133d11_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='conversationsession',
            index=models.Index(fields=['user', '-created_at'], name='django_ergo_user_id_29480d_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationsession',
            index=models.Index(fields=['status'], name='django_ergo_status_16acbe_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationsession',
            index=models.Index(fields=['engine_type'], name='django_ergo_engine__f11924_idx'),
        ),
        migrations.AddIndex(
            model_name='claudemessage',
            index=models.Index(fields=['session', 'sequence'], name='django_ergo_session_ed808c_idx'),
        ),
        migrations.AddIndex(
            model_name='openaimessage',
            index=models.Index(fields=['session', 'sequence'], name='django_ergo_session_98e389_idx'),
        ),
    ]
