# Generated by Django 5.2.6 on 2026-03-31 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ergo', '0004_conversationsession_claudemessage_openaimessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claudemessage',
            name='cache_creation_input_tokens',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claudemessage',
            name='cache_read_input_tokens',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claudemessage',
            name='model_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='openaimessage',
            name='model_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
