# Generated by Django 5.2.6 on 2026-04-03 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ergo', '0005_claudemessage_cache_creation_input_tokens_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationKBUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mode', models.CharField(choices=[('read', 'Read'), ('write', 'Write'), ('suggest', 'Suggest')], max_length=10)),
                ('knowledgebase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_usages', to='django_ergo.knowledgebase')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kb_usages', to='django_ergo.conversationsession')),
            ],
            options={
                'unique_together': {('session', 'knowledgebase', 'mode')},
            },
        ),
    ]
