# Generated by Django 5.2.6 on 2026-04-11 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ergo', '0007_remove_cli_transport_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationsession',
            name='transport_type',
            field=models.CharField(choices=[('api', 'API')], max_length=20),
        ),
    ]
