# Generated by Django 5.2.12 on 2026-08-22 15:01

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ergo', '0010_knowledgesource_sourcedocument_alter_article_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgesource',
            name='index_config_hash',
            field=models.CharField(blank=True, default='', editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='knowledgesource',
            name='index_embedding_id',
            field=models.CharField(blank=True, default='', editable=False, max_length=512),
        ),
        migrations.AddField(
            model_name='knowledgesource',
            name='last_indexed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='knowledgesource',
            name='last_indexed_commit',
            field=models.CharField(blank=True, editable=False, max_length=40, null=True),
        ),
        migrations.CreateModel(
            name='SourceFile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relative_path', models.CharField(max_length=1024)),
                ('prior_paths', models.JSONField(blank=True, default=list)),
                ('git_blob_oid', models.CharField(max_length=64)),
                ('language', models.CharField(max_length=32)),
                ('source_role', models.CharField(max_length=64)),
                ('content_hash', models.CharField(max_length=64)),
                ('last_indexed_commit', models.CharField(max_length=40)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_files', to='django_ergo.knowledgesource')),
            ],
        ),
        migrations.CreateModel(
            name='SourceUnit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unit_key', models.CharField(max_length=1024)),
                ('prior_keys', models.JSONField(blank=True, default=list)),
                ('kind', models.CharField(max_length=64)),
                ('symbol', models.CharField(blank=True, default='', max_length=512)),
                ('qualified_name', models.CharField(blank=True, default='', max_length=1024)),
                ('start_line', models.PositiveIntegerField()),
                ('end_line', models.PositiveIntegerField()),
                ('signature', models.TextField(blank=True, default='')),
                ('lexical_text', models.TextField()),
                ('evidence_text', models.TextField()),
                ('content_hash', models.CharField(max_length=64)),
                ('embedding_input_hash', models.CharField(max_length=64)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('source_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='django_ergo.sourcefile')),
            ],
        ),
        migrations.CreateModel(
            name='SourceRelation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relation_type', models.CharField(max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_relations', to='django_ergo.knowledgesource')),
                ('from_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relations', to='django_ergo.sourceunit')),
                ('to_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relations', to='django_ergo.sourceunit')),
            ],
        ),
        migrations.AddIndex(
            model_name='sourcefile',
            index=models.Index(fields=['source', 'relative_path'], name='django_ergo_source__dc8fdc_idx'),
        ),
        migrations.AddConstraint(
            model_name='sourcefile',
            constraint=models.UniqueConstraint(fields=('source', 'relative_path'), name='source_file_path_unique'),
        ),
        migrations.AddIndex(
            model_name='sourceunit',
            index=models.Index(fields=['source_file', 'kind'], name='django_ergo_source__8db849_idx'),
        ),
        migrations.AddIndex(
            model_name='sourceunit',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='source_unit_search_gin'),
        ),
        migrations.AddIndex(
            model_name='sourceunit',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='source_unit_embedding_hnsw', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddConstraint(
            model_name='sourceunit',
            constraint=models.UniqueConstraint(fields=('source_file', 'unit_key'), name='source_unit_key_unique'),
        ),
        migrations.AddIndex(
            model_name='sourcerelation',
            index=models.Index(fields=['source', 'relation_type'], name='django_ergo_source__95a16c_idx'),
        ),
        migrations.AddConstraint(
            model_name='sourcerelation',
            constraint=models.UniqueConstraint(fields=('source', 'from_unit', 'to_unit', 'relation_type'), name='source_relation_unique'),
        ),
    ]
