# Generated by Django 6.1.1 on 2026-10-01 22:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_ergo", "0014_path_primary_articles"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="conversationsession",
            name="bot_name",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="conversationsession",
            name="compaction_config",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="conversationsession",
            name="compaction_mode",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("time", "Time-based"),
                    ("context_size", "Context size"),
                    ("stream", "Stream"),
                ],
                default="none",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="conversationsession",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="django_ergo.conversationsession",
            ),
        ),
        migrations.AddField(
            model_name="conversationsession",
            name="system_prompt",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.CreateModel(
            name="StructuredCall",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("kind", models.CharField(max_length=64)),
                ("request", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In progress"),
                            ("awaiting_approval", "Awaiting approval"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("turn_limited", "Turn limited"),
                        ],
                        default="in_progress",
                        max_length=20,
                    ),
                ),
                ("response", models.JSONField(blank=True, null=True)),
                ("error", models.TextField(blank=True, default="")),
                (
                    "error_category",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("turns_used", models.IntegerField(default=0)),
                (
                    "engine_type",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "model_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("system_prompt", models.TextField(blank=True, default="")),
                ("transcript", models.JSONField(blank=True, default=list)),
                ("first_sequence", models.IntegerField(blank=True, null=True)),
                ("last_sequence", models.IntegerField(blank=True, null=True)),
                ("input_tokens", models.IntegerField(default=0)),
                ("output_tokens", models.IntegerField(default=0)),
                ("cache_creation_input_tokens", models.IntegerField(default=0)),
                ("cache_read_input_tokens", models.IntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revisions",
                        to="django_ergo.structuredcall",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="structured_calls",
                        to="django_ergo.conversationsession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="structured_calls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConversationCompaction",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("time", "Time-based"),
                            ("context_size", "Context size"),
                            ("stream", "Stream"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reason", models.CharField(blank=True, default="", max_length=255)),
                ("from_sequence", models.IntegerField()),
                ("upto_sequence", models.IntegerField()),
                ("message_count", models.IntegerField(default=0)),
                ("summary", models.TextField()),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compactions",
                        to="django_ergo.conversationsession",
                    ),
                ),
                (
                    "structured_call",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="compactions",
                        to="django_ergo.structuredcall",
                    ),
                ),
            ],
            options={
                "ordering": ["upto_sequence"],
            },
        ),
        migrations.CreateModel(
            name="ConversationAttachment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("message_sequence", models.IntegerField()),
                ("position", models.IntegerField(default=0)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("audio", "Audio"),
                            ("document", "Document"),
                        ],
                        max_length=20,
                    ),
                ),
                ("media_type", models.CharField(max_length=100)),
                (
                    "file",
                    models.FileField(blank=True, upload_to="ergo/attachments/%Y/%m/"),
                ),
                ("url", models.URLField(blank=True, default="", max_length=2000)),
                ("filename", models.CharField(blank=True, default="", max_length=255)),
                ("size", models.IntegerField(blank=True, null=True)),
                ("sha256", models.CharField(blank=True, default="", max_length=64)),
                ("transcript", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="django_ergo.conversationsession",
                    ),
                ),
            ],
            options={
                "ordering": ["message_sequence", "position"],
                "indexes": [
                    models.Index(
                        fields=["session", "message_sequence"],
                        name="django_ergo_session_d4a0e1_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="structuredcall",
            index=models.Index(
                fields=["kind", "-created_at"], name="django_ergo_kind_1550df_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="structuredcall",
            index=models.Index(
                fields=["session", "created_at"], name="django_ergo_session_bfa2bf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversationcompaction",
            index=models.Index(
                fields=["session", "-upto_sequence"],
                name="django_ergo_session_6e8d29_idx",
            ),
        ),
    ]
