# Generated by Django 6.1.1 on 2026-10-01 20:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_ergo", "0014_path_primary_articles"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StructuredOutput",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sequence", models.IntegerField()),
                ("request", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("turn_limited", "Turn limited"),
                        ],
                        default="in_progress",
                        max_length=20,
                    ),
                ),
                ("output", models.JSONField(blank=True, null=True)),
                ("error", models.TextField(blank=True, default="")),
                (
                    "error_category",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("turns_used", models.IntegerField(default=0)),
                ("first_sequence", models.IntegerField(blank=True, null=True)),
                ("last_sequence", models.IntegerField(blank=True, null=True)),
                ("input_tokens", models.IntegerField(default=0)),
                ("output_tokens", models.IntegerField(default=0)),
                ("cache_creation_input_tokens", models.IntegerField(default=0)),
                ("cache_read_input_tokens", models.IntegerField(default=0)),
                (
                    "model_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
            ],
            options={
                "ordering": ["sequence"],
            },
        ),
        migrations.AddField(
            model_name="conversationsession",
            name="kind",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="conversationsession",
            name="mode",
            field=models.CharField(
                choices=[("chat", "Chat"), ("structured", "Structured")],
                default="chat",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="conversationsession",
            name="system_prompt",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddIndex(
            model_name="conversationsession",
            index=models.Index(
                fields=["mode", "kind"], name="django_ergo_mode_dfba76_idx"
            ),
        ),
        migrations.AddField(
            model_name="structuredoutput",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="structured_outputs",
                to="django_ergo.conversationsession",
            ),
        ),
        migrations.AddConstraint(
            model_name="structuredoutput",
            constraint=models.UniqueConstraint(
                fields=("session", "sequence"), name="unique_structured_output_sequence"
            ),
        ),
    ]
