# Generated by Django 6.1.1 on 2026-10-01 20:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_ergo", "0015_structured_sessions"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversationsession",
            name="compaction_config",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="conversationsession",
            name="compaction_mode",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("time", "Time-based"),
                    ("context_size", "Context size"),
                    ("stream", "Stream"),
                ],
                default="none",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ConversationCompaction",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("time", "Time-based"),
                            ("context_size", "Context size"),
                            ("stream", "Stream"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reason", models.CharField(blank=True, default="", max_length=255)),
                ("from_sequence", models.IntegerField()),
                ("upto_sequence", models.IntegerField()),
                ("message_count", models.IntegerField(default=0)),
                ("summary", models.TextField()),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compactions",
                        to="django_ergo.conversationsession",
                    ),
                ),
            ],
            options={
                "ordering": ["upto_sequence"],
                "indexes": [
                    models.Index(
                        fields=["session", "-upto_sequence"],
                        name="django_ergo_session_6e8d29_idx",
                    )
                ],
            },
        ),
    ]
