# Generated by Django 4.2.23 on 2026-10-02 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_ergo", "0015_conversation_runtime"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversationattachment",
            name="source",
            field=models.CharField(
                choices=[
                    ("message", "Sent with a message"),
                    ("upload", "Uploaded to the session"),
                    ("bot", "Written by the bot"),
                ],
                default="message",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="conversationattachment",
            name="message_sequence",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
