# Generated by Django 6.1.1 on 2026-10-01 21:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_ergo", "0016_session_compaction"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversationAttachment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("message_sequence", models.IntegerField()),
                ("position", models.IntegerField(default=0)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("audio", "Audio"),
                            ("document", "Document"),
                        ],
                        max_length=20,
                    ),
                ),
                ("media_type", models.CharField(max_length=100)),
                (
                    "file",
                    models.FileField(blank=True, upload_to="ergo/attachments/%Y/%m/"),
                ),
                ("url", models.URLField(blank=True, default="", max_length=2000)),
                ("filename", models.CharField(blank=True, default="", max_length=255)),
                ("size", models.IntegerField(blank=True, null=True)),
                ("sha256", models.CharField(blank=True, default="", max_length=64)),
                ("transcript", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="django_ergo.conversationsession",
                    ),
                ),
            ],
            options={
                "ordering": ["message_sequence", "position"],
                "indexes": [
                    models.Index(
                        fields=["session", "message_sequence"],
                        name="django_ergo_session_d4a0e1_idx",
                    )
                ],
            },
        ),
    ]
