# Generated by Django 4.2.23 on 2026-10-02 02:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("django_ergo", "0016_session_files"),
    ]

    operations = [
        migrations.CreateModel(
            name="ThreadMessage",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("text", models.TextField()),
                ("depth", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("delivered", "Delivered (the recipient is working on it)"),
                            ("waiting", "Waiting for the user's approval"),
                            ("answered", "Answered"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("reply_text", models.TextField(blank=True, default="")),
                ("error", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "in_reply_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replies",
                        to="django_ergo.threadmessage",
                    ),
                ),
                (
                    "recipient_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thread_messages",
                        to="django_ergo.conversationsession",
                    ),
                ),
                (
                    "sender_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_thread_messages",
                        to="django_ergo.conversationsession",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient_session", "status"],
                        name="django_ergo_recipie_c85cd3_idx",
                    )
                ],
            },
        ),
    ]
