# Generated by Django 4.2.23 on 2026-10-02 04:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("django_ergo", "0017_thread_messages"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduleRun",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bot_name", models.CharField(max_length=100)),
                ("schedule", models.CharField(max_length=100)),
                ("minute", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="schedulerun",
            constraint=models.UniqueConstraint(
                fields=("bot_name", "schedule", "user", "minute"),
                name="unique_schedule_run",
            ),
        ),
    ]
