# Generated by Django 6.1.1 on 2026-10-01 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_ergo", "0017_message_attachments"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversationsession",
            name="bot_name",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="conversationsession",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="django_ergo.conversationsession",
            ),
        ),
    ]
