# Generated by Django 4.2.23 on 2026-10-02 05:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("django_ergo", "0019_root_chats_are_main"),
    ]

    operations = [
        migrations.CreateModel(
            name="BotJob",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bot_name", models.CharField(db_index=True, max_length=100)),
                ("name", models.CharField(max_length=200)),
                ("target", models.CharField(max_length=300)),
                ("args", models.JSONField(blank=True, default=dict)),
                ("status", models.CharField(default="pending", max_length=20)),
                ("progress", models.PositiveSmallIntegerField(default=0)),
                ("result", models.JSONField(blank=True, null=True)),
                ("error", models.TextField(blank=True, default="")),
                ("traceback", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
