# Generated by Django 4.2.23 on 2026-10-02 18:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("django_ergo", "0020_bot_jobs"),
    ]

    operations = [
        migrations.CreateModel(
            name="Worker",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("bot_name", models.CharField(db_index=True, max_length=100)),
                ("title", models.CharField(max_length=200)),
                ("function", models.CharField(max_length=200)),
                ("args", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("progress", models.TextField(blank=True, default="")),
                ("state", models.JSONField(blank=True, default=dict)),
                ("result", models.JSONField(blank=True, null=True)),
                ("error", models.TextField(blank=True, default="")),
                ("notify", models.BooleanField(default=True)),
                ("polls", models.PositiveIntegerField(default=0)),
                ("next_poll_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workers",
                        to="django_ergo.conversationsession",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["session", "status"],
                        name="django_ergo_session_eeeff0_idx",
                    )
                ],
            },
        ),
    ]
