# Generated by Django 6.1.1 on 2026-10-02 19:48

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("django_ergo", "0021_workers"),
    ]

    operations = [
        migrations.AddField(
            model_name="openaimessage",
            name="cache_read_input_tokens",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
