# Generated by Django 4.2.23 on 2026-10-02 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_ergo", "0022_openai_cached_tokens"),
    ]

    operations = [
        migrations.AddField(
            model_name="openaimessage",
            name="cache_creation_input_tokens",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="openaimessage",
            name="reasoning_tokens",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="structuredcall",
            name="cost_usd",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="structuredcall",
            name="reasoning_tokens",
            field=models.IntegerField(default=0),
        ),
    ]
