# Generated by Django 4.2.23 on 2026-10-02 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_ergo", "0023_usage_parts"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversationsession",
            name="read_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
