# Generated by Django 6.1.1 on 2026-10-02 20:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_ergo", "0023_usage_parts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="structuredcall",
            name="status",
            field=models.CharField(
                choices=[
                    ("in_progress", "In progress"),
                    ("awaiting_approval", "Awaiting approval"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("turn_limited", "Turn limited"),
                    ("stopped", "Stopped"),
                ],
                default="in_progress",
                max_length=20,
            ),
        ),
    ]
