# Generated by Django 4.2.23 on 2026-10-04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("django_ergo", "0030_engine_neutral_messages")]

    operations = [
        migrations.CreateModel(
            name="AgentUsage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("bot_name", models.CharField(db_index=True, max_length=100)),
                ("source", models.CharField(default="orca", max_length=20)),
                ("agent", models.CharField(max_length=20)),
                ("model", models.CharField(max_length=200)),
                ("input_tokens", models.PositiveBigIntegerField(default=0)),
                ("cache_write_tokens", models.PositiveBigIntegerField(default=0)),
                ("cache_read_tokens", models.PositiveBigIntegerField(default=0)),
                ("output_tokens", models.PositiveBigIntegerField(default=0)),
                ("reasoning_tokens", models.PositiveBigIntegerField(default=0)),
                ("requests", models.PositiveIntegerField(default=0)),
                ("first_at", models.DateTimeField(blank=True, null=True)),
                ("last_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_usage",
                        to="django_ergo.conversationsession",
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_usage",
                        to="django_ergo.worker",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["session", "last_at"],
                        name="django_ergo_session_c0d858_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("worker", "model"), name="agent_usage_worker_model"
                    )
                ],
            },
        )
    ]
