# Generated by Django 4.2.23 on 2026-10-05 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_ergo", "0031_agent_usage"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProviderUsage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=100, unique=True)),
                ("windows", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="RoutingPolicy",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_sha", models.CharField(max_length=64, unique=True)),
                ("source", models.TextField(blank=True, default="")),
                ("rules", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
